try other GH Action

diff --git a/.github/workflows/build-exe-pyinstaller.yml b/.github/workflows/build-exe-pyinstaller.yml
--- a/.github/workflows/build-exe-pyinstaller.yml
+++ b/.github/workflows/build-exe-pyinstaller.yml
@@ -12,69 +12,74 @@ jobs:
   build:
     runs-on: windows-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
+      - uses: actions/checkout@v6
 
-      - name: Install Python
-        uses: actions/setup-python@v6
+      - name: Package Application
+        uses: JackMcKew/pyinstaller-action-windows@main
         with:
-          python-version: 3.12
+          path: .
+          spec: ./pyinstaller.spec
 
-      - name: Install Python dev tools
-        shell: bash
-        run: |
-          python -m pip install -U pip
-          python -m pip install wheel setuptools
+      # - name: Install Python
+      #   uses: actions/setup-python@v6
+      #   with:
+      #     python-version: 3.12
 
-      - name: Install project
-        shell: bash
-        run: python -m pip install .
+      # - name: Install Python dev tools
+      #   shell: bash
+      #   run: |
+      #     python -m pip install -U pip
+      #     python -m pip install wheel setuptools
 
-      - name: Install PyInstaller
-        shell: bash
-        run: |
-          python -m pip install pyinstaller
-          # Install Kivy window/audio dependencies explicitly for Windows
-          python -m pip install kivy.deps.sdl2 kivy.deps.glew pypiwin32
+      # - name: Install project
+      #   shell: bash
+      #   run: python -m pip install .
 
-      - name: Install build prereqs
-        if: false # skip step for now
-        shell: powershell
-        run: |
-          # Install OpenGL support
-          $version = "26.1.1"
-          $url = "https://github.com/pal1000/mesa-dist-win/releases/download/$version/mesa3d-$version-release-mingw.7z"
-          Invoke-WebRequest -Uri "$url" -OutFile "mesa.7z"
-          & "${env:ProgramFiles}/7-Zip/7z.exe" x "mesa.7z" -o"mesa" -y
-          # Copy DLLs to pyinstaller directory.
-          $PYINSTALLER_DIR = "${env:Python_ROOT_DIR}\Scripts"
-          Write-Host $PYTHON_DIR
-          Copy-Item "mesa/x64/*" -Destination "$PYINSTALLER_DIR"
-          dir "$PYINSTALLER_DIR"
-          # Add DLLs folder to $PATH
-          # $env:Path += ";${{ env.GITHUB_WORKSPACE }}/mesa/x64/"
+      # - name: Install PyInstaller
+      #   shell: bash
+      #   run: |
+      #     python -m pip install pyinstaller
+      #     # Install Kivy window/audio dependencies explicitly for Windows
+      #     python -m pip install kivy.deps.sdl2 kivy.deps.glew pypiwin32
 
-      - name: Set env variables to override kivy checks
-        if: false
-        shell: bash
-        run: |
-          echo "KIVY_NO_CONSOLE=1" >> $GITHUB_ENV
-          echo "KIVY_NO_KIVY_CONFIG=1" >> $GITHUB_ENV
-          echo "USE_SDL2=1" >> $GITHUB_ENV
-          echo "USE_GSTREAMER=1" >> $GITHUB_ENV
+      # - name: Install build prereqs
+      #   if: false # skip step for now
+      #   shell: powershell
+      #   run: |
+      #     # Install OpenGL support
+      #     $version = "26.1.1"
+      #     $url = "https://github.com/pal1000/mesa-dist-win/releases/download/$version/mesa3d-$version-release-mingw.7z"
+      #     Invoke-WebRequest -Uri "$url" -OutFile "mesa.7z"
+      #     & "${env:ProgramFiles}/7-Zip/7z.exe" x "mesa.7z" -o"mesa" -y
+      #     # Copy DLLs to pyinstaller directory.
+      #     $PYINSTALLER_DIR = "${env:Python_ROOT_DIR}\Scripts"
+      #     Write-Host $PYTHON_DIR
+      #     Copy-Item "mesa/x64/*" -Destination "$PYINSTALLER_DIR"
+      #     dir "$PYINSTALLER_DIR"
+      #     # Add DLLs folder to $PATH
+      #     # $env:Path += ";${{ env.GITHUB_WORKSPACE }}/mesa/x64/"
 
-      - name: Run PyInstaller
-        shell: bash
-        env:
-          KIVY_NO_ARGS: 1
-          KIVY_WINDOW: dummy
-        run: |
-          pyinstaller \
-            --clean \
-            --noconfirm \
-            --exclude-module="kivy.core.window.window_sdl2" \
-            pyinstaller.spec
-          echo "return code = $?"
+      # - name: Set env variables to override kivy checks
+      #   if: false
+      #   shell: bash
+      #   run: |
+      #     echo "KIVY_NO_CONSOLE=1" >> $GITHUB_ENV
+      #     echo "KIVY_NO_KIVY_CONFIG=1" >> $GITHUB_ENV
+      #     echo "USE_SDL2=1" >> $GITHUB_ENV
+      #     echo "USE_GSTREAMER=1" >> $GITHUB_ENV
+
+      # - name: Run PyInstaller
+      #   shell: bash
+      #   env:
+      #     KIVY_NO_ARGS: 1
+      #     KIVY_WINDOW: dummy
+      #   run: |
+      #     pyinstaller \
+      #       --clean \
+      #       --noconfirm \
+      #       --exclude-module="kivy.core.window.window_sdl2" \
+      #       pyinstaller.spec
+      #     echo "return code = $?"
 
       # - name: Build EXE with PyInstaller Action
       #   uses: n8marti/pyinstaller@main
@@ -87,13 +92,13 @@ jobs:
       #     upload_exe_with_name: "NetworkPuzzles"
       #     clean_checkout: false # don't remove existing files from workdir
 
-      - name: Check sys info
-        if: false # skip for now
-        shell: bash
-        run: |
-          env | sort
-          ls -l ${RUNNER_TOOL_CACHE}\\Python\\3.12.10\\x64\\Scripts\\
-          ls -l ${RUNNER_TOOL_CACHE}\\Python\\3.12.10\\x64\\Lib\\site-packages\\
+      # - name: Check sys info
+      #   if: false # skip for now
+      #   shell: bash
+      #   run: |
+      #     env | sort
+      #     ls -l ${RUNNER_TOOL_CACHE}\\Python\\3.12.10\\x64\\Scripts\\
+      #     ls -l ${RUNNER_TOOL_CACHE}\\Python\\3.12.10\\x64\\Lib\\site-packages\\
 
       - name: Upload Executable
         id: artifact_upload
@@ -103,17 +108,17 @@ jobs:
           path: ./dist
           compression-level: 0
 
-      - name: Upload kivy logs
-        if: always()
-        uses: actions/upload-artifact@v7
-        with:
-          name: kivy-logs
-          include-hidden-files: true
-          path: ~\\.kivy\\logs\\*.txt
+      # - name: Upload kivy logs
+      #   if: always()
+      #   uses: actions/upload-artifact@v7
+      #   with:
+      #     name: kivy-logs
+      #     include-hidden-files: true
+      #     path: ~\\.kivy\\logs\\*.txt
 
-      - name: Upload pyinstaller logs
-        if: always()
-        uses: actions/upload-artifact@v7
-        with:
-          name: pyinstaller-logs
-          path: ${{ github.workspace }}\\build\\pyinstaller\\*.txt
+      # - name: Upload pyinstaller logs
+      #   if: always()
+      #   uses: actions/upload-artifact@v7
+      #   with:
+      #     name: pyinstaller-logs
+      #     path: ${{ github.workspace }}\\build\\pyinstaller\\*.txt
